name: Test
on:
  pull_request:
  push:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        pattern: '^\s*(?<trimmed>.*?)\s*$'
        input: ' bla bla '
    - run: |
        [ "${{steps.my_step.outputs.0}}" = " bla bla " ]
        [ "${{steps.my_step.outputs.1}}" =  "bla bla" ]
        [ "${{steps.my_step.outputs.trimmed}}" = "bla bla" ]
